

/* This is auto-generated code. Edit at your own peril. */
#include <stdio.h>
#include <stdlib.h>

#include "CuTest.h"


extern void Test_secp256k1_sign_1(CuTest*);
extern void Test_secp256k1_sign_2(CuTest*);
extern void Test_secp256k1_sign_3(CuTest*);
extern void Test_secp256k1_verify_1(CuTest*);
extern void Test_secp256k1_verify_1b(CuTest*);
extern void Test_secp256k1_verify_2(CuTest*);
extern void Test_secp256k1_verify_2b(CuTest*);
extern void Test_secp256k1_verify_3(CuTest*);
extern void Test_secp256k1_verify_3b(CuTest*);
extern void Test_secp256k1_verify_4(CuTest*);
extern void Test_secp256k1_verify_4b(CuTest*);
extern void Test_secp256k1_verify_5(CuTest*);
extern void Test_secp256k1_verify_5b(CuTest*);
extern void Test_secp256k1_sign_and_verify_1(CuTest*);
extern void Test_secp256k1_sign_and_verify_2(CuTest*);
extern void Testsecp256k1_normalize_s_1(CuTest*);
extern void Testsecp256k1_normalize_s_2(CuTest*);
extern void Testsecp256k1_normalize_s_3(CuTest*);
extern void Testsecp256k1_normalize_s_4(CuTest*);
extern void Testsecp256k1_normalize_s_5(CuTest*);
extern void Testsecp256k1_normalize_s_6(CuTest*);
extern void Test_add_different_points_1(CuTest*);
extern void Test_add_different_points_2(CuTest*);
extern void Test_add_different_points_3(CuTest*);
extern void Test_add_different_points_4(CuTest*);
extern void Test_add_different_points_5(CuTest*);
extern void Test_add_different_points_6(CuTest*);
extern void Test_add_different_points_7(CuTest*);
extern void Test_add_different_points_8(CuTest*);
extern void Test_add_different_points_9(CuTest*);
extern void Test_add_different_points_10(CuTest*);
extern void Test_add_different_points_11(CuTest*);
extern void Test_add_different_points_12(CuTest*);
extern void Test_add_different_points_13(CuTest*);
extern void Test_add_asign_14(CuTest*);
extern void Test_double_point_1(CuTest*);
extern void Test_double_point_2(CuTest*);
extern void Test_double_point_3(CuTest*);
extern void Test_compare_1(CuTest*);
extern void Test_compare_2(CuTest*);
extern void Test_compare_3(CuTest*);
extern void Test_compare_4(CuTest*);
extern void Test_compare_5(CuTest*);
extern void Test_compare_6(CuTest*);
extern void Test_compare_7(CuTest*);
extern void Test_compare_8(CuTest*);
extern void Test_compare_9(CuTest*);
extern void Test_generator_mul_1(CuTest*);
extern void Test_generator_mul_2(CuTest*);
extern void Test_generator_mul_3(CuTest*);
extern void Test_generator_mul_4(CuTest*);
extern void Test_generator_mul_5(CuTest*);
extern void Test_generator_mul_6(CuTest*);
extern void Test_generator_mul_7(CuTest*);
extern void Test_generator_mul_8(CuTest*);
extern void Test_generator_mul_9(CuTest*);
extern void Test_generator_mul_10(CuTest*);
extern void Test_generator_mul_11(CuTest*);
extern void Test_generator_mul_12(CuTest*);
extern void Test_generator_mul_13(CuTest*);
extern void Test_generator_mul_14(CuTest*);
extern void Test_generator_mul_15(CuTest*);
extern void Test_generator_mul_16(CuTest*);
extern void Test_generator_mul_17(CuTest*);
extern void Test_generator_mul_18(CuTest*);
extern void Test_generator_mul_19(CuTest*);
extern void Test_generator_mul_20(CuTest*);
extern void Test_generator_mul_21(CuTest*);
extern void Test_generator_mul_22(CuTest*);
extern void Test_generator_mul_23(CuTest*);
extern void Test_generator_mul_24(CuTest*);
extern void Test_generator_mul_25(CuTest*);
extern void Test_generator_mul_26(CuTest*);
extern void Test_generator_mul_27(CuTest*);
extern void Test_generator_mul_28(CuTest*);
extern void Test_generator_mul_29(CuTest*);
extern void Test_generator_mul_30(CuTest*);
extern void Test_generator_mul_31(CuTest*);
extern void Test_generator_mul_32(CuTest*);
extern void Test_generator_mul_33(CuTest*);
extern void Test_point_mul_1(CuTest*);
extern void Test_point_mul_2(CuTest*);
extern void Test_point_mul_3(CuTest*);
extern void Test_point_mul_asign_1(CuTest*);
extern void Test_point_mul_asign_2(CuTest*);
extern void Test_point_mul_asign_3(CuTest*);
extern void Test_point_mul_asign_4(CuTest*);
extern void Test_point_mul_asign_5(CuTest*);
extern void Test_point_mul_asign_6(CuTest*);
extern void Test_is_point_on_curve_1(CuTest*);
extern void Test_is_point_on_curve_2(CuTest*);
extern void Test_is_point_on_curve_3(CuTest*);
extern void Test_is_point_on_curve_4(CuTest*);
extern void Test_is_point_on_curve_5(CuTest*);
extern void Test_is_point_on_curve_6(CuTest*);
extern void Test_is_point_on_curve_7(CuTest*);
extern void Testsecp256k1_calculate_y_coordinates_from_x_1(CuTest*);
extern void Testsecp256k1_calculate_y_coordinates_from_x_2(CuTest*);
extern void Testsecp256k1_calculate_y_coordinates_from_x_3(CuTest*);
extern void Testsecp256k1_calculate_y_coordinates_from_x_4(CuTest*);
extern void Testsecp256k1_calculate_y_coordinates_from_x_5(CuTest*);
extern void Testsecp256k1_calculate_y_coordinates_from_x_6(CuTest*);
extern void Test_secp256k1_keypair_from_private_key_1(CuTest*);
extern void Test_secp256k1_keypair_from_private_key_2(CuTest*);
extern void Test_secp256k1_keypair_from_private_key_3(CuTest*);
extern void Test_secp256k1_keypair_from_private_key_4(CuTest*);
extern void Testsecp256k1_secp256k1_reduce_mod_n_1(CuTest*);
extern void Testsecp256k1_secp256k1_reduce_mod_n_2(CuTest*);
extern void Testsecp256k1_secp256k1_reduce_mod_n_3(CuTest*);
extern void Testsecp256k1_secp256k1_reduce_mod_n_4(CuTest*);
extern void Testsecp256k1_add_mod_n_1(CuTest*);
extern void Testsecp256k1_add_mod_n_2(CuTest*);
extern void Testsecp256k1_add_mod_n_3(CuTest*);
extern void Testsecp256k1_add_mod_n_4(CuTest*);
extern void Testsecp256k1_add_mod_n_5(CuTest*);
extern void Testsecp256k1_mul_mod_n_1(CuTest*);
extern void Testsecp256k1_mul_mod_n_2(CuTest*);
extern void Testsecp256k1_mul_mod_n_3(CuTest*);
extern void Testsecp256k1_mul_mod_n_4(CuTest*);
extern void Testsecp256k1_mul_mod_n_5(CuTest*);
extern void Testsecp256k1_mul_mod_n_6(CuTest*);
extern void Testsecp256k1_mul_mod_n_7(CuTest*);
extern void Testsecp256k1_mul_mod_n_8(CuTest*);
extern void Testsecp256k1_mul_mod_n_9(CuTest*);
extern void Testsecp256k1_square_mod_n_1(CuTest*);
extern void Testsecp256k1_square_mod_n_2(CuTest*);
extern void TestSecp256k1_square_mod_n_3(CuTest*);
extern void TestSecp256k1_square_mod_n_4(CuTest*);
extern void TestSecp256k1_square_mod_n_5(CuTest*);
extern void TestSecp256k1_square_mod_n_6(CuTest*);
extern void TestSecp256k1_square_mod_n_7(CuTest*);
extern void TestSecp256k1_square_mod_n_8(CuTest*);
extern void TestSecp256k1_square_mod_n_9(CuTest*);
extern void TestSecp256k1_square_mod_n_10(CuTest*);
extern void TestSecp256k1_square_mod_n_11(CuTest*);
extern void TestSecp256k1_square_mod_n_12(CuTest*);
extern void TestSecp256k1_square_mod_n_13(CuTest*);
extern void TestSecp256k1_square_mod_n_asign_1(CuTest*);
extern void TestSecp256k1_square_mod_n_asign_2(CuTest*);
extern void Testsecp256k1_invert_mod_n_1(CuTest*);
extern void Testsecp256k1_invert_mod_n_2(CuTest*);
extern void Testsecp256k1_invert_mod_n_3(CuTest*);
extern void Testsecp256k1_invert_mod_n_4(CuTest*);
extern void Testsecp256k1_invert_mod_n_5(CuTest*);
extern void Testsecp256k1_invert_mod_n_6(CuTest*);
extern void Testsecp256k1_invert_mod_n_7(CuTest*);
extern void Testsecp256k1_invert_mod_n_8(CuTest*);
extern void Testsecp256k1_invert_mod_n_asign_1(CuTest*);
extern void Testsecp256k1_invert_mod_n_asign_2(CuTest*);
extern void Testsecp256k1_sub_mod_n_1(CuTest*);
extern void Testsecp256k1_sub_mod_n_2(CuTest*);
extern void Testsecp256k1_sub_mod_n_3(CuTest*);
extern void Testsecp256k1_sub_mod_n_4(CuTest*);
extern void Testsecp256k1_sub_mod_n_5(CuTest*);
extern void Testsecp256k1_sub_mod_n_6(CuTest*);
extern void Testsecp256k1_sub_mod_n_7(CuTest*);
extern void Testsecp256k1_sub_mod_n_8(CuTest*);
extern void Testsecp256k1_sub_mod_n_9(CuTest*);
extern void Testsecp256k1_sub_mod_n_10(CuTest*);
extern void Testsecp256k1_sub_mod_n_11(CuTest*);
extern void Testsecp256k1_sub_mod_n_12(CuTest*);
extern void Testsecp256k1_sub_mod_n_13(CuTest*);
extern void TestSecp256k1_add_mod_p_1(CuTest*);
extern void TestSecp256k1_add_mod_p_2(CuTest*);
extern void TestSecp256k1_add_mod_p_3(CuTest*);
extern void TestSecp256k1_add_mod_p_4(CuTest*);
extern void TestSecp256k1_add_mod_p_5(CuTest*);
extern void TestSecp256k1_add_mod_p_6(CuTest*);
extern void TestSecp256k1_add_mod_p_7(CuTest*);
extern void TestSecp256k1_add_mod_p_8(CuTest*);
extern void TestSecp256k1_add_mod_p_9(CuTest*);
extern void TestSecp256k1_add_mod_p_10(CuTest*);
extern void TestSecp256k1_add_mod_p_11(CuTest*);
extern void TestSecp256k1_double_mod_p_1(CuTest*);
extern void TestSecp256k1_double_mod_p_2(CuTest*);
extern void TestSecp256k1_double_mod_p_3(CuTest*);
extern void TestSecp256k1_double_mod_p_4(CuTest*);
extern void TestSecp256k1_double_mod_p_5(CuTest*);
extern void TestSecp256k1_double_mod_p_6(CuTest*);
extern void TestSecp256k1_triple_mod_p_1(CuTest*);
extern void TestSecp256k1_triple_mod_p_2(CuTest*);
extern void TestSecp256k1_triple_mod_p_3(CuTest*);
extern void TestSecp256k1_triple_mod_p_4(CuTest*);
extern void TestSecp256k1_triple_mod_p_5(CuTest*);
extern void TestSecp256k1_triple_mod_p_6(CuTest*);
extern void TestSecp256k1_triple_mod_p_7(CuTest*);
extern void TestSecp256k1_triple_mod_p_8(CuTest*);
extern void TestSecp256k1_sub_mod_p_1(CuTest*);
extern void TestSecp256k1_sub_mod_p_2(CuTest*);
extern void TestSecp256k1_sub_mod_p_3(CuTest*);
extern void TestSecp256k1_sub_mod_p_4(CuTest*);
extern void TestSecp256k1_sub_mod_p_5(CuTest*);
extern void TestSecp256k1_sub_mod_p_6(CuTest*);
extern void TestSecp256k1_sub_mod_p_7(CuTest*);
extern void TestSecp256k1_sub_mod_p_8(CuTest*);
extern void TestSecp256k1_negate_mod_p_1(CuTest*);
extern void TestSecp256k1_negate_mod_p_2(CuTest*);
extern void TestSecp256k1_negate_mod_p_3(CuTest*);
extern void TestSecp256k1_negate_mod_p_4(CuTest*);
extern void TestSecp256k1_negate_mod_p_5(CuTest*);
extern void TestSecp256k1_negate_mod_p_6(CuTest*);
extern void TestSecp256k1_negate_mod_p_7(CuTest*);
extern void TestSecp256k1_negate_mod_p_8(CuTest*);
extern void TestSecp256k1_negate_mod_p_asign_1(CuTest*);
extern void TestSecp256k1_negate_mod_p_asign_2(CuTest*);
extern void TestSecp256k1_sub_mod_p_9(CuTest*);
extern void TestSecp256k1_sub_mod_p_10(CuTest*);
extern void TestSecp256k1_sub_mod_p_11(CuTest*);
extern void TestSecp256k1_square_mod_p_1(CuTest*);
extern void TestSecp256k1_square_mod_p_2(CuTest*);
extern void TestSecp256k1_square_mod_p_3(CuTest*);
extern void TestSecp256k1_square_mod_p_4(CuTest*);
extern void TestSecp256k1_square_mod_p_5(CuTest*);
extern void TestSecp256k1_square_mod_p_6(CuTest*);
extern void TestSecp256k1_square_mod_p_7(CuTest*);
extern void TestSecp256k1_square_mod_p_8(CuTest*);
extern void TestSecp256k1_square_mod_p_9(CuTest*);
extern void TestSecp256k1_square_mod_p_10(CuTest*);
extern void TestSecp256k1_square_mod_p_11(CuTest*);
extern void TestSecp256k1_square_mod_p_asign_1(CuTest*);
extern void TestSecp256k1_square_mod_p_asign_2(CuTest*);
extern void Testsecp256k1_invert_mod_p_1(CuTest*);
extern void Testsecp256k1_invert_mod_p_2(CuTest*);
extern void Testsecp256k1_invert_mod_p_3(CuTest*);
extern void Testsecp256k1_invert_mod_p_4(CuTest*);
extern void Testsecp256k1_invert_mod_p_5(CuTest*);
extern void Testsecp256k1_invert_mod_p_6(CuTest*);
extern void Testsecp256k1_invert_mod_p_7(CuTest*);
extern void Testsecp256k1_invert_mod_p_8(CuTest*);
extern void Testsecp256k1_invert_mod_p_asign_1(CuTest*);
extern void Testsecp256k1_invert_mod_p_asign_2(CuTest*);
extern void Testsecp256k1_invert_mod_p_asign_3(CuTest*);
extern void Testsecp256k1_invert_mod_p_asign_4(CuTest*);
extern void Testsecp256k1_invert_mod_p_asign_5(CuTest*);
extern void Testsecp256k1_invert_mod_p_asign_6(CuTest*);
extern void Testsecp256k1_invert_mod_p_asign_7(CuTest*);
extern void Testsecp256k1_invert_mod_p_asign_8(CuTest*);
extern void Testsecp256k1_exponentiate_mod_p1(CuTest*);
extern void Testsecp256k1_exponentiate_mod_p2(CuTest*);
extern void Testsecp256k1_exponentiate_mod_p3(CuTest*);
extern void Testsecp256k1_exponentiate_mod_p4(CuTest*);
extern void Testsecp256k1_exponentiate_mod_p5(CuTest*);
extern void Testsecp256k1_exponentiate_mod_p6(CuTest*);
extern void Testsecp256k1_exponentiate_mod_p7(CuTest*);
extern void Testsecp256k1_cube_mod_p_1(CuTest*);
extern void Testsecp256k1_cube_mod_p_2(CuTest*);
extern void Testsecp256k1_cube_mod_p_asign_1(CuTest*);
extern void Testsecp256k1_cube_mod_p_asign_2(CuTest*);
extern void Testsecp256k1_squareroot_mod_p_1(CuTest*);
extern void Testsecp256k1_squareroot_mod_p_2(CuTest*);
extern void Testsecp256k1_squareroot_mod_p_3(CuTest*);
extern void Testsecp256k1_squareroot_mod_p_4(CuTest*);
extern void Testsecp256k1_squareroot_mod_p_5(CuTest*);
extern void Testsecp256k1_squareroot_mod_p_6(CuTest*);
extern void Testsecp256k1_squareroot_mod_p_7(CuTest*);
extern void Testsecp256k1_squareroot_mod_p_asign_1(CuTest*);
extern void Testsecp256k1_squareroot_mod_p_asign_2(CuTest*);
extern void Testsecp256k1_has_squareroot_mod_p_1(CuTest*);
extern void Testsecp256k1_has_squareroot_mod_p_2(CuTest*);
extern void Testsecp256k1_has_squareroot_mod_p_3(CuTest*);
extern void Testsecp256k1_has_squareroot_mod_p_4(CuTest*);
extern void Testsecp256k1_has_squareroot_mod_p_5(CuTest*);
extern void Testsecp256k1_has_squareroot_mod_p_6(CuTest*);
extern void Testsecp256k1_has_squareroot_mod_p_7(CuTest*);
extern void Testsecp256k1_has_squareroot_mod_p_8(CuTest*);
extern void Testsecp256k1_has_squareroot_mod_p_9(CuTest*);
extern void TestSecp256k1_mul_mod_p_1(CuTest*);
extern void TestSecp256k1_mul_mod_p_2(CuTest*);
extern void TestSecp256k1_mul_mod_p_3(CuTest*);
extern void TestSecp256k1_mul_mod_p_4(CuTest*);
extern void TestSecp256k1_mul_mod_p_5(CuTest*);
extern void TestSecp256k1_mul_mod_p_6(CuTest*);
extern void TestSecp256k1_mul_mod_p_7(CuTest*);
extern void TestSecp256k1_mul_mod_p_8(CuTest*);
extern void TestSecp256k1_mul_mod_p_9(CuTest*);
extern void TestSecp256k1_mul_mod_p_10(CuTest*);
extern void TestSecp256k1_mul_mod_p_11(CuTest*);
extern void TestSecp256k1_mul_mod_p_12(CuTest*);
extern void TestSecp256k1_mul_mod_p_13(CuTest*);
extern void TestSecp256k1_mul_mod_p_14(CuTest*);
extern void TestSecp256k1_parse_point_1(CuTest*);
extern void TestSecp256k1_parse_point_2(CuTest*);
extern void TestSecp256k1_parse_point_3(CuTest*);
extern void TestSecp256k1_parse_point_4(CuTest*);
extern void TestSecp256k1_parse_point_5(CuTest*);
extern void TestSecp256k1_parse_point_6(CuTest*);
extern void TestSecp256k1_parse_point_7(CuTest*);
extern void TestSecp256k1_parse_point_8(CuTest*);
extern void TestSecp256k1_parse_point_9(CuTest*);
extern void TestSecp256k1_parse_point_10(CuTest*);
extern void TestSecp256k1_parse_point_11(CuTest*);
extern void TestSecp256k1_parse_point_12(CuTest*);
extern void TestSecp256k1_parse_point_13(CuTest*);
extern void Testsecp256k1_parse_scalar_1(CuTest*);
extern void Testsecp256k1_parse_scalar_2(CuTest*);
extern void Testsecp256k1_parse_scalar_3(CuTest*);
extern void Testsecp256k1_parse_scalar_4(CuTest*);
extern void Testsecp256k1_parse_u64_1(CuTest*);
extern void Testsecp256k1_parse_u64_2(CuTest*);
extern void Testsecp256k1_parse_u64_3(CuTest*);
extern void Test_mul512_1(CuTest*);
extern void Test_mul512_2(CuTest*);
extern void Test_mul512_3(CuTest*);
extern void Test_mul512_4(CuTest*);
extern void Test_mul512_5(CuTest*);
extern void Test_mul512_6(CuTest*);
extern void Test_mul512_7(CuTest*);
extern void Test_square512_1(CuTest*);
extern void Test_square512_2(CuTest*);
extern void Test_square512_3(CuTest*);
extern void Test_square512_4(CuTest*);
extern void Test_square512_5(CuTest*);
extern void Test_square512_6(CuTest*);
extern void Test_square512_7(CuTest*);


void RunAllTests(void) 
{
    CuString *output = CuStringNew();
    CuSuite* suite = CuSuiteNew();


    SUITE_ADD_TEST(suite, Test_secp256k1_sign_1);
    SUITE_ADD_TEST(suite, Test_secp256k1_sign_2);
    SUITE_ADD_TEST(suite, Test_secp256k1_sign_3);
    SUITE_ADD_TEST(suite, Test_secp256k1_verify_1);
    SUITE_ADD_TEST(suite, Test_secp256k1_verify_1b);
    SUITE_ADD_TEST(suite, Test_secp256k1_verify_2);
    SUITE_ADD_TEST(suite, Test_secp256k1_verify_2b);
    SUITE_ADD_TEST(suite, Test_secp256k1_verify_3);
    SUITE_ADD_TEST(suite, Test_secp256k1_verify_3b);
    SUITE_ADD_TEST(suite, Test_secp256k1_verify_4);
    SUITE_ADD_TEST(suite, Test_secp256k1_verify_4b);
    SUITE_ADD_TEST(suite, Test_secp256k1_verify_5);
    SUITE_ADD_TEST(suite, Test_secp256k1_verify_5b);
    SUITE_ADD_TEST(suite, Test_secp256k1_sign_and_verify_1);
    SUITE_ADD_TEST(suite, Test_secp256k1_sign_and_verify_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_normalize_s_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_normalize_s_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_normalize_s_3);
    SUITE_ADD_TEST(suite, Testsecp256k1_normalize_s_4);
    SUITE_ADD_TEST(suite, Testsecp256k1_normalize_s_5);
    SUITE_ADD_TEST(suite, Testsecp256k1_normalize_s_6);
    SUITE_ADD_TEST(suite, Test_add_different_points_1);
    SUITE_ADD_TEST(suite, Test_add_different_points_2);
    SUITE_ADD_TEST(suite, Test_add_different_points_3);
    SUITE_ADD_TEST(suite, Test_add_different_points_4);
    SUITE_ADD_TEST(suite, Test_add_different_points_5);
    SUITE_ADD_TEST(suite, Test_add_different_points_6);
    SUITE_ADD_TEST(suite, Test_add_different_points_7);
    SUITE_ADD_TEST(suite, Test_add_different_points_8);
    SUITE_ADD_TEST(suite, Test_add_different_points_9);
    SUITE_ADD_TEST(suite, Test_add_different_points_10);
    SUITE_ADD_TEST(suite, Test_add_different_points_11);
    SUITE_ADD_TEST(suite, Test_add_different_points_12);
    SUITE_ADD_TEST(suite, Test_add_different_points_13);
    SUITE_ADD_TEST(suite, Test_add_asign_14);
    SUITE_ADD_TEST(suite, Test_double_point_1);
    SUITE_ADD_TEST(suite, Test_double_point_2);
    SUITE_ADD_TEST(suite, Test_double_point_3);
    SUITE_ADD_TEST(suite, Test_compare_1);
    SUITE_ADD_TEST(suite, Test_compare_2);
    SUITE_ADD_TEST(suite, Test_compare_3);
    SUITE_ADD_TEST(suite, Test_compare_4);
    SUITE_ADD_TEST(suite, Test_compare_5);
    SUITE_ADD_TEST(suite, Test_compare_6);
    SUITE_ADD_TEST(suite, Test_compare_7);
    SUITE_ADD_TEST(suite, Test_compare_8);
    SUITE_ADD_TEST(suite, Test_compare_9);
    SUITE_ADD_TEST(suite, Test_generator_mul_1);
    SUITE_ADD_TEST(suite, Test_generator_mul_2);
    SUITE_ADD_TEST(suite, Test_generator_mul_3);
    SUITE_ADD_TEST(suite, Test_generator_mul_4);
    SUITE_ADD_TEST(suite, Test_generator_mul_5);
    SUITE_ADD_TEST(suite, Test_generator_mul_6);
    SUITE_ADD_TEST(suite, Test_generator_mul_7);
    SUITE_ADD_TEST(suite, Test_generator_mul_8);
    SUITE_ADD_TEST(suite, Test_generator_mul_9);
    SUITE_ADD_TEST(suite, Test_generator_mul_10);
    SUITE_ADD_TEST(suite, Test_generator_mul_11);
    SUITE_ADD_TEST(suite, Test_generator_mul_12);
    SUITE_ADD_TEST(suite, Test_generator_mul_13);
    SUITE_ADD_TEST(suite, Test_generator_mul_14);
    SUITE_ADD_TEST(suite, Test_generator_mul_15);
    SUITE_ADD_TEST(suite, Test_generator_mul_16);
    SUITE_ADD_TEST(suite, Test_generator_mul_17);
    SUITE_ADD_TEST(suite, Test_generator_mul_18);
    SUITE_ADD_TEST(suite, Test_generator_mul_19);
    SUITE_ADD_TEST(suite, Test_generator_mul_20);
    SUITE_ADD_TEST(suite, Test_generator_mul_21);
    SUITE_ADD_TEST(suite, Test_generator_mul_22);
    SUITE_ADD_TEST(suite, Test_generator_mul_23);
    SUITE_ADD_TEST(suite, Test_generator_mul_24);
    SUITE_ADD_TEST(suite, Test_generator_mul_25);
    SUITE_ADD_TEST(suite, Test_generator_mul_26);
    SUITE_ADD_TEST(suite, Test_generator_mul_27);
    SUITE_ADD_TEST(suite, Test_generator_mul_28);
    SUITE_ADD_TEST(suite, Test_generator_mul_29);
    SUITE_ADD_TEST(suite, Test_generator_mul_30);
    SUITE_ADD_TEST(suite, Test_generator_mul_31);
    SUITE_ADD_TEST(suite, Test_generator_mul_32);
    SUITE_ADD_TEST(suite, Test_generator_mul_33);
    SUITE_ADD_TEST(suite, Test_point_mul_1);
    SUITE_ADD_TEST(suite, Test_point_mul_2);
    SUITE_ADD_TEST(suite, Test_point_mul_3);
    SUITE_ADD_TEST(suite, Test_point_mul_asign_1);
    SUITE_ADD_TEST(suite, Test_point_mul_asign_2);
    SUITE_ADD_TEST(suite, Test_point_mul_asign_3);
    SUITE_ADD_TEST(suite, Test_point_mul_asign_4);
    SUITE_ADD_TEST(suite, Test_point_mul_asign_5);
    SUITE_ADD_TEST(suite, Test_point_mul_asign_6);
    SUITE_ADD_TEST(suite, Test_is_point_on_curve_1);
    SUITE_ADD_TEST(suite, Test_is_point_on_curve_2);
    SUITE_ADD_TEST(suite, Test_is_point_on_curve_3);
    SUITE_ADD_TEST(suite, Test_is_point_on_curve_4);
    SUITE_ADD_TEST(suite, Test_is_point_on_curve_5);
    SUITE_ADD_TEST(suite, Test_is_point_on_curve_6);
    SUITE_ADD_TEST(suite, Test_is_point_on_curve_7);
    SUITE_ADD_TEST(suite, Testsecp256k1_calculate_y_coordinates_from_x_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_calculate_y_coordinates_from_x_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_calculate_y_coordinates_from_x_3);
    SUITE_ADD_TEST(suite, Testsecp256k1_calculate_y_coordinates_from_x_4);
    SUITE_ADD_TEST(suite, Testsecp256k1_calculate_y_coordinates_from_x_5);
    SUITE_ADD_TEST(suite, Testsecp256k1_calculate_y_coordinates_from_x_6);
    SUITE_ADD_TEST(suite, Test_secp256k1_keypair_from_private_key_1);
    SUITE_ADD_TEST(suite, Test_secp256k1_keypair_from_private_key_2);
    SUITE_ADD_TEST(suite, Test_secp256k1_keypair_from_private_key_3);
    SUITE_ADD_TEST(suite, Test_secp256k1_keypair_from_private_key_4);
    SUITE_ADD_TEST(suite, Testsecp256k1_secp256k1_reduce_mod_n_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_secp256k1_reduce_mod_n_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_secp256k1_reduce_mod_n_3);
    SUITE_ADD_TEST(suite, Testsecp256k1_secp256k1_reduce_mod_n_4);
    SUITE_ADD_TEST(suite, Testsecp256k1_add_mod_n_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_add_mod_n_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_add_mod_n_3);
    SUITE_ADD_TEST(suite, Testsecp256k1_add_mod_n_4);
    SUITE_ADD_TEST(suite, Testsecp256k1_add_mod_n_5);
    SUITE_ADD_TEST(suite, Testsecp256k1_mul_mod_n_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_mul_mod_n_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_mul_mod_n_3);
    SUITE_ADD_TEST(suite, Testsecp256k1_mul_mod_n_4);
    SUITE_ADD_TEST(suite, Testsecp256k1_mul_mod_n_5);
    SUITE_ADD_TEST(suite, Testsecp256k1_mul_mod_n_6);
    SUITE_ADD_TEST(suite, Testsecp256k1_mul_mod_n_7);
    SUITE_ADD_TEST(suite, Testsecp256k1_mul_mod_n_8);
    SUITE_ADD_TEST(suite, Testsecp256k1_mul_mod_n_9);
    SUITE_ADD_TEST(suite, Testsecp256k1_square_mod_n_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_square_mod_n_2);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_n_3);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_n_4);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_n_5);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_n_6);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_n_7);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_n_8);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_n_9);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_n_10);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_n_11);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_n_12);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_n_13);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_n_asign_1);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_n_asign_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_n_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_n_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_n_3);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_n_4);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_n_5);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_n_6);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_n_7);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_n_8);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_n_asign_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_n_asign_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_sub_mod_n_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_sub_mod_n_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_sub_mod_n_3);
    SUITE_ADD_TEST(suite, Testsecp256k1_sub_mod_n_4);
    SUITE_ADD_TEST(suite, Testsecp256k1_sub_mod_n_5);
    SUITE_ADD_TEST(suite, Testsecp256k1_sub_mod_n_6);
    SUITE_ADD_TEST(suite, Testsecp256k1_sub_mod_n_7);
    SUITE_ADD_TEST(suite, Testsecp256k1_sub_mod_n_8);
    SUITE_ADD_TEST(suite, Testsecp256k1_sub_mod_n_9);
    SUITE_ADD_TEST(suite, Testsecp256k1_sub_mod_n_10);
    SUITE_ADD_TEST(suite, Testsecp256k1_sub_mod_n_11);
    SUITE_ADD_TEST(suite, Testsecp256k1_sub_mod_n_12);
    SUITE_ADD_TEST(suite, Testsecp256k1_sub_mod_n_13);
    SUITE_ADD_TEST(suite, TestSecp256k1_add_mod_p_1);
    SUITE_ADD_TEST(suite, TestSecp256k1_add_mod_p_2);
    SUITE_ADD_TEST(suite, TestSecp256k1_add_mod_p_3);
    SUITE_ADD_TEST(suite, TestSecp256k1_add_mod_p_4);
    SUITE_ADD_TEST(suite, TestSecp256k1_add_mod_p_5);
    SUITE_ADD_TEST(suite, TestSecp256k1_add_mod_p_6);
    SUITE_ADD_TEST(suite, TestSecp256k1_add_mod_p_7);
    SUITE_ADD_TEST(suite, TestSecp256k1_add_mod_p_8);
    SUITE_ADD_TEST(suite, TestSecp256k1_add_mod_p_9);
    SUITE_ADD_TEST(suite, TestSecp256k1_add_mod_p_10);
    SUITE_ADD_TEST(suite, TestSecp256k1_add_mod_p_11);
    SUITE_ADD_TEST(suite, TestSecp256k1_double_mod_p_1);
    SUITE_ADD_TEST(suite, TestSecp256k1_double_mod_p_2);
    SUITE_ADD_TEST(suite, TestSecp256k1_double_mod_p_3);
    SUITE_ADD_TEST(suite, TestSecp256k1_double_mod_p_4);
    SUITE_ADD_TEST(suite, TestSecp256k1_double_mod_p_5);
    SUITE_ADD_TEST(suite, TestSecp256k1_double_mod_p_6);
    SUITE_ADD_TEST(suite, TestSecp256k1_triple_mod_p_1);
    SUITE_ADD_TEST(suite, TestSecp256k1_triple_mod_p_2);
    SUITE_ADD_TEST(suite, TestSecp256k1_triple_mod_p_3);
    SUITE_ADD_TEST(suite, TestSecp256k1_triple_mod_p_4);
    SUITE_ADD_TEST(suite, TestSecp256k1_triple_mod_p_5);
    SUITE_ADD_TEST(suite, TestSecp256k1_triple_mod_p_6);
    SUITE_ADD_TEST(suite, TestSecp256k1_triple_mod_p_7);
    SUITE_ADD_TEST(suite, TestSecp256k1_triple_mod_p_8);
    SUITE_ADD_TEST(suite, TestSecp256k1_sub_mod_p_1);
    SUITE_ADD_TEST(suite, TestSecp256k1_sub_mod_p_2);
    SUITE_ADD_TEST(suite, TestSecp256k1_sub_mod_p_3);
    SUITE_ADD_TEST(suite, TestSecp256k1_sub_mod_p_4);
    SUITE_ADD_TEST(suite, TestSecp256k1_sub_mod_p_5);
    SUITE_ADD_TEST(suite, TestSecp256k1_sub_mod_p_6);
    SUITE_ADD_TEST(suite, TestSecp256k1_sub_mod_p_7);
    SUITE_ADD_TEST(suite, TestSecp256k1_sub_mod_p_8);
    SUITE_ADD_TEST(suite, TestSecp256k1_negate_mod_p_1);
    SUITE_ADD_TEST(suite, TestSecp256k1_negate_mod_p_2);
    SUITE_ADD_TEST(suite, TestSecp256k1_negate_mod_p_3);
    SUITE_ADD_TEST(suite, TestSecp256k1_negate_mod_p_4);
    SUITE_ADD_TEST(suite, TestSecp256k1_negate_mod_p_5);
    SUITE_ADD_TEST(suite, TestSecp256k1_negate_mod_p_6);
    SUITE_ADD_TEST(suite, TestSecp256k1_negate_mod_p_7);
    SUITE_ADD_TEST(suite, TestSecp256k1_negate_mod_p_8);
    SUITE_ADD_TEST(suite, TestSecp256k1_negate_mod_p_asign_1);
    SUITE_ADD_TEST(suite, TestSecp256k1_negate_mod_p_asign_2);
    SUITE_ADD_TEST(suite, TestSecp256k1_sub_mod_p_9);
    SUITE_ADD_TEST(suite, TestSecp256k1_sub_mod_p_10);
    SUITE_ADD_TEST(suite, TestSecp256k1_sub_mod_p_11);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_p_1);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_p_2);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_p_3);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_p_4);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_p_5);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_p_6);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_p_7);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_p_8);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_p_9);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_p_10);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_p_11);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_p_asign_1);
    SUITE_ADD_TEST(suite, TestSecp256k1_square_mod_p_asign_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_p_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_p_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_p_3);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_p_4);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_p_5);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_p_6);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_p_7);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_p_8);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_p_asign_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_p_asign_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_p_asign_3);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_p_asign_4);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_p_asign_5);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_p_asign_6);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_p_asign_7);
    SUITE_ADD_TEST(suite, Testsecp256k1_invert_mod_p_asign_8);
    SUITE_ADD_TEST(suite, Testsecp256k1_exponentiate_mod_p1);
    SUITE_ADD_TEST(suite, Testsecp256k1_exponentiate_mod_p2);
    SUITE_ADD_TEST(suite, Testsecp256k1_exponentiate_mod_p3);
    SUITE_ADD_TEST(suite, Testsecp256k1_exponentiate_mod_p4);
    SUITE_ADD_TEST(suite, Testsecp256k1_exponentiate_mod_p5);
    SUITE_ADD_TEST(suite, Testsecp256k1_exponentiate_mod_p6);
    SUITE_ADD_TEST(suite, Testsecp256k1_exponentiate_mod_p7);
    SUITE_ADD_TEST(suite, Testsecp256k1_cube_mod_p_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_cube_mod_p_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_cube_mod_p_asign_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_cube_mod_p_asign_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_squareroot_mod_p_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_squareroot_mod_p_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_squareroot_mod_p_3);
    SUITE_ADD_TEST(suite, Testsecp256k1_squareroot_mod_p_4);
    SUITE_ADD_TEST(suite, Testsecp256k1_squareroot_mod_p_5);
    SUITE_ADD_TEST(suite, Testsecp256k1_squareroot_mod_p_6);
    SUITE_ADD_TEST(suite, Testsecp256k1_squareroot_mod_p_7);
    SUITE_ADD_TEST(suite, Testsecp256k1_squareroot_mod_p_asign_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_squareroot_mod_p_asign_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_has_squareroot_mod_p_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_has_squareroot_mod_p_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_has_squareroot_mod_p_3);
    SUITE_ADD_TEST(suite, Testsecp256k1_has_squareroot_mod_p_4);
    SUITE_ADD_TEST(suite, Testsecp256k1_has_squareroot_mod_p_5);
    SUITE_ADD_TEST(suite, Testsecp256k1_has_squareroot_mod_p_6);
    SUITE_ADD_TEST(suite, Testsecp256k1_has_squareroot_mod_p_7);
    SUITE_ADD_TEST(suite, Testsecp256k1_has_squareroot_mod_p_8);
    SUITE_ADD_TEST(suite, Testsecp256k1_has_squareroot_mod_p_9);
    SUITE_ADD_TEST(suite, TestSecp256k1_mul_mod_p_1);
    SUITE_ADD_TEST(suite, TestSecp256k1_mul_mod_p_2);
    SUITE_ADD_TEST(suite, TestSecp256k1_mul_mod_p_3);
    SUITE_ADD_TEST(suite, TestSecp256k1_mul_mod_p_4);
    SUITE_ADD_TEST(suite, TestSecp256k1_mul_mod_p_5);
    SUITE_ADD_TEST(suite, TestSecp256k1_mul_mod_p_6);
    SUITE_ADD_TEST(suite, TestSecp256k1_mul_mod_p_7);
    SUITE_ADD_TEST(suite, TestSecp256k1_mul_mod_p_8);
    SUITE_ADD_TEST(suite, TestSecp256k1_mul_mod_p_9);
    SUITE_ADD_TEST(suite, TestSecp256k1_mul_mod_p_10);
    SUITE_ADD_TEST(suite, TestSecp256k1_mul_mod_p_11);
    SUITE_ADD_TEST(suite, TestSecp256k1_mul_mod_p_12);
    SUITE_ADD_TEST(suite, TestSecp256k1_mul_mod_p_13);
    SUITE_ADD_TEST(suite, TestSecp256k1_mul_mod_p_14);
    SUITE_ADD_TEST(suite, TestSecp256k1_parse_point_1);
    SUITE_ADD_TEST(suite, TestSecp256k1_parse_point_2);
    SUITE_ADD_TEST(suite, TestSecp256k1_parse_point_3);
    SUITE_ADD_TEST(suite, TestSecp256k1_parse_point_4);
    SUITE_ADD_TEST(suite, TestSecp256k1_parse_point_5);
    SUITE_ADD_TEST(suite, TestSecp256k1_parse_point_6);
    SUITE_ADD_TEST(suite, TestSecp256k1_parse_point_7);
    SUITE_ADD_TEST(suite, TestSecp256k1_parse_point_8);
    SUITE_ADD_TEST(suite, TestSecp256k1_parse_point_9);
    SUITE_ADD_TEST(suite, TestSecp256k1_parse_point_10);
    SUITE_ADD_TEST(suite, TestSecp256k1_parse_point_11);
    SUITE_ADD_TEST(suite, TestSecp256k1_parse_point_12);
    SUITE_ADD_TEST(suite, TestSecp256k1_parse_point_13);
    SUITE_ADD_TEST(suite, Testsecp256k1_parse_scalar_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_parse_scalar_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_parse_scalar_3);
    SUITE_ADD_TEST(suite, Testsecp256k1_parse_scalar_4);
    SUITE_ADD_TEST(suite, Testsecp256k1_parse_u64_1);
    SUITE_ADD_TEST(suite, Testsecp256k1_parse_u64_2);
    SUITE_ADD_TEST(suite, Testsecp256k1_parse_u64_3);
    SUITE_ADD_TEST(suite, Test_mul512_1);
    SUITE_ADD_TEST(suite, Test_mul512_2);
    SUITE_ADD_TEST(suite, Test_mul512_3);
    SUITE_ADD_TEST(suite, Test_mul512_4);
    SUITE_ADD_TEST(suite, Test_mul512_5);
    SUITE_ADD_TEST(suite, Test_mul512_6);
    SUITE_ADD_TEST(suite, Test_mul512_7);
    SUITE_ADD_TEST(suite, Test_square512_1);
    SUITE_ADD_TEST(suite, Test_square512_2);
    SUITE_ADD_TEST(suite, Test_square512_3);
    SUITE_ADD_TEST(suite, Test_square512_4);
    SUITE_ADD_TEST(suite, Test_square512_5);
    SUITE_ADD_TEST(suite, Test_square512_6);
    SUITE_ADD_TEST(suite, Test_square512_7);

    CuSuiteRun(suite);
    CuSuiteSummary(suite, output);
    CuSuiteDetails(suite, output);
    printf("%s\n", output->buffer);
    CuStringDelete(output);
    CuSuiteDelete(suite);
}

int main(void)
{
    printf("\nTesting finite field and elliptic curve functions on the secp256k1 curve.\n");
    RunAllTests();
}

